name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'python/requirements.txt'
      - run: pip install -r python/requirements.txt
      - name: Lint (flake8)
        run: flake8 python
      - name: Tests (pytest)
        run: pytest -q

  test-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests in docker-compose
        run: |
          docker compose -f docker-compose.dev.yml up --build --exit-code-from tests tests
      - name: Clean up
        if: always()
        run: |
          docker compose -f docker-compose.dev.yml down -v
